/*
break lablea; * SelectSiteDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nms.ui.ptn.basicinfo.dialog.site;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JTextField;
import twaver.Element;
import twaver.Node;
import com.nms.db.bean.equipment.shelf.SiteInst;
import com.nms.ui.Ptnf;
import com.nms.ui.manager.ConstantUtil;
import com.nms.ui.manager.DialogBoxUtil;
import com.nms.ui.manager.ExceptionManage;
import com.nms.ui.manager.ResourceUtil;
import com.nms.ui.manager.keys.StringKeysBtn;
import com.nms.ui.manager.keys.StringKeysLbl;
import com.nms.ui.manager.keys.StringKeysMenu;
import com.nms.ui.manager.keys.StringKeysObj;
import com.nms.ui.manager.keys.StringKeysTab;
import com.nms.ui.manager.keys.StringKeysTip;
import com.nms.ui.manager.keys.StringKeysTitle;
import com.nms.ui.topology.NetworkElementPanel;

/**
 * 
 * @author __USER__
 */
public class SelectSiteDialog1 extends javax.swing.JDialog {

	private static final long serialVersionUID = -6365870649459079127L;
	private Boolean siteIdexist = false;

	/** Creates new form SelectSiteDialog */
	public SelectSiteDialog1(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public SelectSiteDialog1(boolean modal) {
		this.setModal(modal);
		initComponents();
		this.setTitle(ResourceUtil.srcStr(StringKeysMenu.MENU_SELECTSITE));
		addActionListener();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(ResourceUtil.srcStr(StringKeysTitle.TIT_SELECT_SITE)));

		jButton1.setText(ResourceUtil.srcStr(StringKeysBtn.BTN_SAVE));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText(ResourceUtil.srcStr(StringKeysBtn.BTN_CANEL));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setText(ResourceUtil.srcStr(StringKeysObj.STRING_SITE_NAME));

		jLabel2.setText(ResourceUtil.srcStr(StringKeysLbl.LBL_SITE_IP));

		jLabel3.setText(ResourceUtil.srcStr(StringKeysLbl.LBL_SITE_TYPE));

		jLabel4.setText(ResourceUtil.srcStr(StringKeysLbl.LBL_SITE_ID));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton2).addGap(10, 10, 10)).addGroup(
								jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1).addComponent(jLabel3).addComponent(jLabel2).addComponent(jLabel4)).addGap(43, 43, 43).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE).addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE).addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)).addGap(55, 55, 55)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel4)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE).addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1).addComponent(jButton2))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	@SuppressWarnings("unchecked")
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {		
		try {
			dispose();
			Ptnf.getPtnf().mainTabPanel(ConstantUtil.jTabbedPane, ResourceUtil.srcStr(StringKeysTab.TAB_TOPO), NetworkElementPanel.getNetworkElementPanel());				
		    List<Element> elementList = null;	
		    List<Element> elementList1 = NetworkElementPanel.getNetworkElementPanel().getNetwork().getDataBox().getAllElements();
		    elementList = NetworkElementPanel.getNetworkElementPanel().getNetwork().getDataBox().getAllElements();
		    for (Element element : elementList) {
			    if (element instanceof Node) {
			    	if (element.getUserObject() instanceof SiteInst) {
					    SiteInst siteInst = (SiteInst) element.getUserObject();
					    
					    if (jTextField1.getText().length() > 0) {
					    	if (!siteInst.getCellId().contains(jTextField1.getText().trim())) {
					    		if(elementList1.contains(element)){
							    	  elementList1.remove(element);
								   }
						    }
					    }
					    if (jTextField2.getText().length() > 0) {
						    if (!siteInst.getCellDescribe().contains(jTextField2.getText().trim())) {
							   if(elementList1.contains(element)){
						    	  elementList1.remove(element);
							   }
						    }
					    }
					    if (jTextField3.getText().length() > 0) {
						    if (!siteInst.getCellType().contains(jTextField3.getText().trim())) {
						    	if(elementList1.contains(element)){
							    	  elementList1.remove(element);
								   }
						    }
					    }
					    if (jTextField4.getText().length() > 0) {
					    	if (!(siteInst.getSite_Inst_Id()==Integer.parseInt(jTextField4.getText().trim()))) {
					    		if(elementList1.contains(element)){
							    	  elementList1.remove(element);
								   }
						    }
					    }

				      }
			      }
		     }    
		    if(elementList1 !=null  && elementList1.size() >0){		    	
		       for (Element element1 : elementList1) {		    	   
		    		  if (element1 instanceof Node) {		    			  
		    			  if (element1.getUserObject() instanceof SiteInst) {		    				  
		    		          element1.setSelected(true);		    		          
		    		          if (element1.isSelected()) {	
		    		        	  NetworkElementPanel.getNetworkElementPanel().getNetwork().centerElement(element1);
		    		             siteIdexist = true;
		    		          }
		    		          
		    			  }
		    	       }
		    	 }
		    }
		    if (!siteIdexist) {
			    DialogBoxUtil.errorDialog(NetworkElementPanel.getNetworkElementPanel(), ResourceUtil.srcStr(StringKeysTip.TIP_SITENONENTILY));			 
		    }
		} catch (Exception e) {
			ExceptionManage.dispose(e,this.getClass());
		}
	}

	private void addActionListener() {
		this.jTextField1.addKeyListener(new KeyAdapter() {
			public void keyTyped(KeyEvent evt) {
				if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
					jButton1ActionPerformed(null);
				}

			}

		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				SelectSiteDialog1 dialog = new SelectSiteDialog1(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
	
	public JTextField getJtextField1() {
		return jTextField1;
	}

	public void setJtextField1(JTextField jTextField1) {
		this.jTextField1 = jTextField1;
	}
	public JTextField getJtextField2() {
		return jTextField2;
	}

	public void setJtextField2(JTextField jTextField2) {
		this.jTextField2 = jTextField2;
	}
	public JTextField getJtextField3() {
		return jTextField3;
	}

	public void setJtextField3(JTextField jTextField3) {
		this.jTextField3 = jTextField3;
	}
	public JTextField getJtextField4() {
		return jTextField4;
	}

	public void setJtextField4(JTextField jTextField4) {
		this.jTextField4 = jTextField4;
	}
	public Boolean getSiteIdexist() {
		return siteIdexist;
	}

	public void setSiteIdexist(Boolean siteIdexist) {
		this.siteIdexist = siteIdexist;
	}
}