/*
 * UDPServer.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nms.drive.network.ui;

import com.nms.drive.network.UDPNetworkServer;
import com.nms.ui.manager.ExceptionManage;

/**
 * 
 * @author __USER__
 */
public class UDPServer extends javax.swing.JFrame {

	public javax.swing.JMenuItem getExitMenuItem() {
		return exitMenuItem;
	}

	public void setExitMenuItem(javax.swing.JMenuItem exitMenuItem) {
		this.exitMenuItem = exitMenuItem;
	}

	public javax.swing.JMenu getFileMenu() {
		return fileMenu;
	}

	public void setFileMenu(javax.swing.JMenu fileMenu) {
		this.fileMenu = fileMenu;
	}

	public javax.swing.JButton getJButton1() {
		return jButton1;
	}

	public void setJButton1(javax.swing.JButton button1) {
		jButton1 = button1;
	}

	public javax.swing.JButton getJButton2() {
		return jButton2;
	}

	public void setJButton2(javax.swing.JButton button2) {
		jButton2 = button2;
	}

	public javax.swing.JLabel getJLabel1() {
		return jLabel1;
	}

	public void setJLabel1(javax.swing.JLabel label1) {
		jLabel1 = label1;
	}

	public javax.swing.JLabel getJLabel2() {
		return jLabel2;
	}

	public void setJLabel2(javax.swing.JLabel label2) {
		jLabel2 = label2;
	}

	public javax.swing.JLabel getJLabel3() {
		return jLabel3;
	}

	public void setJLabel3(javax.swing.JLabel label3) {
		jLabel3 = label3;
	}

	public javax.swing.JScrollPane getJScrollPane1() {
		return jScrollPane1;
	}

	public void setJScrollPane1(javax.swing.JScrollPane scrollPane1) {
		jScrollPane1 = scrollPane1;
	}

	public javax.swing.JSeparator getJSeparator1() {
		return jSeparator1;
	}

	public void setJSeparator1(javax.swing.JSeparator separator1) {
		jSeparator1 = separator1;
	}

	public javax.swing.JTextArea getJTextArea1() {
		return jTextArea1;
	}

	public void setJTextArea1(javax.swing.JTextArea textArea1) {
		jTextArea1 = textArea1;
	}

	public javax.swing.JTextField getJTextField1() {
		return jTextField1;
	}

	public void setJTextField1(javax.swing.JTextField textField1) {
		jTextField1 = textField1;
	}

	/** Creates new form UDPServer */
	public UDPServer() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		exitMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("UDP\u670d\u52a1\u7aef");
		setResizable(false);

		jButton1.setText("\u542f\u52a8");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jScrollPane1.setAutoscrolls(true);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextField1.setText("9999");

		jLabel1.setText("\u7aef\u53e3\uff1a");

		jButton2.setText("\u505c\u6b62");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel2.setText("\u72b6\u6001\uff1a");

		jLabel3.setText("....");

		fileMenu.setText("\u6587\u4ef6");

		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		setJMenuBar(menuBar);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE).addContainerGap()).add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE).add(layout.createSequentialGroup().add(jLabel2).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE).addContainerGap())).add(org.jdesktop.layout.GroupLayout.TRAILING,
								layout.createSequentialGroup().add(jLabel1).add(11, 11, 11).add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(20, 20, 20)))));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel1).add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jButton2).add(jButton1)).add(7, 7, 7).add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 319, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
						layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2).add(jLabel3)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}

	public UDPNetworkServer UDPNetworkServer = null;

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			UDPNetworkServer.close();
			UDPNetworkServer = null;
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "关闭成功");
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "--------------------------");
		} catch (Exception e) {
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + e.getMessage());
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "--------------------------");
			ExceptionManage.dispose(e,this.getClass());
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			UDPNetworkServer = new UDPNetworkServer();
			UDPNetworkServer.connection("", 0, Integer.valueOf(jTextField1.getText()));
			MessageTh MessageTh = new MessageTh();
			MessageTh.setUDPServer(this);
			MessageTh.start();
			this.jTextArea1.setText("");
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "启动成功");
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "--------------------------");
		} catch (Exception e) {
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + e.getMessage());
			jTextArea1.setText(jTextArea1.getText() + "\r\n" + "--------------------------");
			ExceptionManage.dispose(e,this.getClass());
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UDPServer().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JMenuBar menuBar;
	// End of variables declaration//GEN-END:variables

}